### ISSUE TITLE
Remove override keyword when format

### ISSUE THREAD

**Issue by FilipLaurentiu** [juanfranblanco/vscode-solidity#174] opened 2020-05-08 11:37 UTC
It remove override keyword automatic when format.
This is very annoying

**Comment by abcoathup** [comment] 2020-05-20 05:33
Formatting a contract with the override keyword results in the override keyword being removed
## Unformatted
```solidity
pragma solidity ^0.6.0;


contract A {
    function doStuff() public virtual {}
}


contract B is A {
    function doStuff() public override {}
}
```
## Formatted
```solidity
pragma solidity ^0.6.0;


contract A {
    function doStuff() public virtual {}
}


contract B is A {
    function doStuff() public {}
}
```

I assume that the issue is potentially with `prettier-solidity` 
https://github.com/prettier-solidity/prettier-plugin-solidity/issues/277

**Comment by juanfranblanco** [comment] 2021-01-06 12:15
Closing this has been fixed for a while

**Closed by juanfranblanco** 2021-01-06 12:15 UTC
