### ISSUE TITLE
Jump to function definition is not working

### ISSUE THREAD

**Issue by Jonathan-Livingston-Seagull** [juanfranblanco/vscode-solidity#244] opened 2021-05-21 08:13 UTC
Hi, Jump to function definition is not working. When I press F12, it shows no definition found for the function. I use following configuration

`
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-53-generic
solidity: v0.0.113
 "solidity.compileUsingRemoteVersion": "v0.7.3+commit.9bfce1f6"`

Could you please assist me in this?

**Comment by juanfranblanco** [comment] 2021-05-21 08:15
@Jonathan-Livingston-Seagull are you using open zeppelin 4?

**Comment by Jonathan-Livingston-Seagull** [comment] 2021-05-21 08:20
@juanfranblanco Thanks for the quick response. How do I check which version of open zeppelin I am using? Sorry I am a beginner in block chain development.

**Comment by juanfranblanco** [comment] 2021-05-21 08:22
If you are using the latest, this might be an issue with some syntax parsing that I am yet to solve with some contracts (and new solidity version)

**Comment by Jonathan-Livingston-Seagull** [comment] 2021-05-21 08:28
@juanfranblanco I see, I am trying to reproduce a token that I copied from , and there they do not have any imports from openzeppelin but copied around the necessary parts. So unfortunately I would not know from which version of openzeppelin those contents are copied from. But I strongly doubt that , they copied from the latest version and It match up with the issue you are describing. Is there any ETA on solving this issue as it is an important feature :)

**Comment by juanfranblanco** [comment] 2021-05-21 08:29
I am busy with Nethereum eip1559 and other bits, i need 2 solid days to fix this.

**Comment by juanfranblanco** [comment] 2021-05-21 08:31
It might be just configuration btw.

**Comment by Jonathan-Livingston-Seagull** [comment] 2021-05-21 08:31
@juanfranblanco I think, I found a workaround I guess :), when I enable solc-vscode extensions, I am able to jump to definition, would not it make sense to integrate that in our extension?

**Comment by juanfranblanco** [comment] 2021-05-21 08:33
Which one is that..

**Comment by Jonathan-Livingston-Seagull** [comment] 2021-05-21 08:36
The extension: https://github.com/rocky/solc-vscode and the code to the contract https://gist.github.com/Jonathan-Livingston-Seagull/ef490a57a6175d80c64e8c95b48b839a

**Comment by juanfranblanco** [comment] 2021-05-21 08:37
What version are you using of vscode? That is pretty old and it will break with new syntax.

**Comment by juanfranblanco** [comment] 2021-05-21 08:39
Ill have a look :) This is not related to new syntax.

**Comment by Jonathan-Livingston-Seagull** [comment] 2021-05-21 08:41
Visual studio version : 1.56.2. Ok, I will split the contract into multiple files and update here. Thanks

**Comment by juanfranblanco** [comment] 2021-05-21 08:42
ah cool, I am doing it now any way as I am curious.

**Comment by Jonathan-Livingston-Seagull** [comment] 2021-05-21 09:08
@juanfranblanco  Separating contracts did not help on my side :( Please let me know if you get things working on your side.

**Comment by juanfranblanco** [comment] 2021-05-21 09:32
ah read hearring..

The issue is with this:

This is the try catch syntax i need to fix. I you comment it out, autocomplete etc will work now.
```
/*
        //If for whatever reason the swap cannot be made, return false without
        //failing the whole transaction
        try uniswapV2Router.swapExactTokensForETHSupportingFeeOnTransferTokens(
            tokenAmount,
            0, // accept any amount of ETH
            path,
            address(this),
            block.timestamp
        ) {
            return true;
        } catch( bytes memory) {
            return false;
        }
        */
```

Regarding rockys and other parsers we talked about, and I was pushing for that, BUT this will only work when everything is perfect, so autocomplete, go to definition etc won't work with simple incorrect syntax. 
Interesting that you have found that out :)

**Comment by juanfranblanco** [comment] 2021-05-21 09:45
Closing this issue now as this is here #232

**Comment by Jonathan-Livingston-Seagull** [comment] 2021-05-21 09:46
@juanfranblanco  Nice, Perfect. Would have been nice though if the syntax error is highlighted, Could be another wish list ;)

**Closed** 2021-05-21 09:45 UTC

**Comment by juanfranblanco** [comment] 2021-05-21 09:48
Yeah, although that is an error internal with the parser, so for an end user might not be ideal. BUT for me to identify the issue yeah :). Something like, parsing issue found.. please raise an issue..

**Comment by juanfranblanco** [comment] 2021-05-21 09:52
So yeah everything is ok, I will try this weekend to get it sorted as it is pretty annoying. (issue on the solid time)
![image](https://user-images.githubusercontent.com/562371/119118912-98ca9600-ba22-11eb-9b0d-b25d9ca4d61d.png)

**Comment by juanfranblanco** [comment] 2021-05-21 13:41
@Jonathan-Livingston-Seagull  give it a go now.

**Comment by Jonathan-Livingston-Seagull** [comment] 2021-05-21 18:53
Yes, it works fine now after commenting out the troubled part. Thanks

**Comment by juanfranblanco** [comment] 2021-05-22 05:37
I meant check the latest, as it is fixed now. @Jonathan-Livingston-Seagull

**Comment by Jonathan-Livingston-Seagull** [comment] 2021-05-22 09:11
Yep. I can confirm that it works now with the fix.
