### ISSUE TITLE
Using local or remote solc doesn't seem to work

### ISSUE THREAD

**Issue by mifeng** [juanfranblanco/vscode-solidity#33] opened 2017-09-12 18:08 UTC
As described in the documentation, I added `"solidity.compileUsingRemoteVersion"` or `"solidity.compileUsingLocalVersion"` to User Settings, but when I compile a contract, it looks like the compiler is still the latest version, not the version I specified in settings.

VSCode version 1.16.0, vscode-solidity version 0.0.29

**Comment by juanfranblanco** [comment] 2017-09-14 12:24
Thanks, what version did you use?

**Comment by mifeng** [comment] 2017-09-14 16:23
Versions:
* VSCode version 1.16.0
* vscode-solidity version 0.0.29

In user settings:
```
"solidity.compileUsingLocalVersion" : "/Users/feng/Code/fund-protocol/node_modules/solc/soljson.js"
```

In `package.json`:
```
  "dependencies": {
    "solc": "0.4.13",
    ...
}
```

Upon compilation of a file with `pragma solidity 0.4.13;`:
```
/Users/feng/Code/fund-protocol/contracts/Fund.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.4.15+commit.bbb8e64f.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.13;
```

**Comment by juanfranblanco** [comment] 2017-09-15 05:07
Thanks, Ill have a look, I assume you are using a Mac. BTW if you have installed in the project locally solc (node package) it will resolve that first and ignore the other settings (as they are global)

**Comment by oliverkai** [comment] 2017-09-25 15:25
I have installed solc in the project's node_modules and the problem is still there

![default](https://user-images.githubusercontent.com/10908687/30816427-852b3f64-a248-11e7-97c7-954f0074a15b.png)

**Comment by juanfranblanco** [comment] 2017-09-27 11:53
@oliverkai  Thanks, ill have a look tonight, been busy with Nethereum.

**Comment by naddison36** [comment] 2017-10-09 11:19
I have the same problem. Is this fix going to be released soon? Thanks @juanfranblanco

**Comment by juanfranblanco** [comment] 2017-10-13 14:50
ok I have found the problem with node, (that took a while) mainly it loads the new solc but it could not recognise the version as this comes from the file string.

Re the others, I need to do further testing as it is fine on my pc.

**Comment by juanfranblanco** [comment] 2017-10-20 17:32
Fixed now on the latest release, keeping it open for feedback.

**Comment by naddison36** [comment] 2017-10-21 21:54
I can confirm this is now working. Thanks a heap @juanfranblanco 
I suggest you close this issue

**Comment by juanfranblanco** [comment] 2017-10-23 07:09
Thanks @naddison36 :)

**Closed by juanfranblanco** 2017-10-23 07:09 UTC

**Comment by Fi1osof** [comment] 2018-04-21 01:06
I have same problem. Ubuntu 17 x64. vscode and vscode-solidity are latest. 
Try to set user settings (different variants)
{
    ....
    "[solidity]": {
        "solidity.compileUsingRemoteVersion" : "0.4.23+commit.124ca40d",
        "compileUsingRemoteVersion" : "0.4.23+commit.124ca40d"
    },
    "solidity.compileUsingRemoteVersion" : "0.4.23+commit.124ca40d"
}
And install solc^0.4.23.
Nothing helps;

.../Rates.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.4.20+commit.3155dd80.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.23;

**Comment by stobiema** [comment] 2018-04-21 09:26
Same error as above. Can't use truffle as always get the solidity is a nightly build error.

**Comment by juanfranblanco** [comment] 2018-04-21 11:11
Tested in Ubuntu and no issues, have you tried using "latest" as the setting?

**Comment by juanfranblanco** [comment] 2018-04-21 11:11
@stobiema @Fi1osof

**Comment by juanfranblanco** [comment] 2018-04-21 11:32
Ok, I have just published a new version with 23 as the integrated compiler.

**Comment by Fi1osof** [comment] 2018-04-22 03:37
@juanfranblanco 
>  have you tried using "latest" as the setting?
Yes, did;
> "solidity.compileUsingRemoteVersion": "v0.4.23+commit.124ca40d",
Tried this one too. Not helps.

**Comment by juanfranblanco** [comment] 2018-04-22 05:42
Then it is a problem with your setup, have you tried uninstalling the extension and maybe other solidity extensions as it has been proved to be conflicting? Then reinstalling it again?

**Comment by Fi1osof** [comment] 2018-04-23 06:39
@juanfranblanco, sorry, it's my mistake.
I have 2 node_modules
./node_modules/solc
./server/node_modules/solc
and was got nearest solc. 
After upgrade ./node_modules/solc all works fine. 
Thanks!

**Comment by juanfranblanco** [comment] 2018-04-23 11:36
Oh yes, the local node_modules takes preference from other settings. As you may want to target a specific version for a project.

**Comment by juanfranblanco** [comment] 2018-04-23 11:38
@Fi1osof  I should have thought about mentioning that first. I have updated the Readme to clarify this a couple of days ago to clarify the order of compiler preference.

**Comment by Fi1osof** [comment] 2018-04-23 15:39
@juanfranblanco thanks a lot!
