### ISSUE TITLE
Support OpenZeppelin Contracts with default settings

### ISSUE THREAD

**Issue by abcoathup** [juanfranblanco/vscode-solidity#178] opened 2020-05-20 05:24 UTC
When importing from OpenZeppelin Contracts installed via npm the default settings of the plugin give a compiler error. `File import callback not supported`

<img width="552" alt="File import callback not supported" src="https://user-images.githubusercontent.com/28278242/82407883-ac5cbd00-9aad-11ea-9d0f-a6fbd0eaec25.png">

It would be great if importing OpenZeppelin Contracts could be supported with default settings.

The default settings include:
```
"solidity.packageDefaultDependenciesContractsDirectory": "contracts"
```
Users need to change the setting from `contracts` to an `empty` string.
```
"solidity.packageDefaultDependenciesContractsDirectory": ""
```

Example contract with OpenZeppelin Contracts installed (`npm i @openzeppelin/contracts`)
```solidity
pragma solidity ^0.6.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract GLDToken is ERC20 {
    constructor(uint256 initialSupply) ERC20("Gold", "GLD") public {
        _mint(msg.sender, initialSupply);
    }
}
```

**Comment by juanfranblanco** [comment] 2020-05-20 16:01
@abcoathup So i guess the ask is to detect the import and validate the settings?

**Comment by juanfranblanco** [comment] 2020-05-20 16:03
@abcoathup, @caleteet was suggesting something similar to detect the solidity version, I guess that will fit rather well in the prompt process.. (prompt for solidity compiler version, if not the same and prompt to set zeppelin settings if not set)

**Comment by caleteeter** [comment] 2020-05-20 18:56
Working on it, should have something very soon.  The virtual events are attempting to slow me down.  :)

**Comment by thegostep** [comment] 2020-06-28 17:53
Looking forward to this!

**Comment by albertov19** [comment] 2021-02-23 10:59
Hi guys,

So I was using @abcoathup example in this thread. I grabbed that contract put it into a `test.sol` file in project root, installed openZeppelin and I do have:

```
"solidity.packageDefaultDependenciesContractsDirectory": ""
"solidity.packageDefaultDependenciesDirectory": "node_modules"
```

And I still get the File Import error. Any ideas?

**Comment by juanfranblanco** [comment] 2021-02-23 11:07
Hi @albertov19 , those settings are by default now as node_modules has become the standard to distribute libraries. Can you post an screenshot of your project structure with the file?

**Comment by albertov19** [comment] 2021-02-23 11:55
Got it, I had to remove `node_modules` from the settings that I had and it worked.

Thanks for this great extension!

**Comment by juanfranblanco** [comment] 2021-02-23 11:56
Excellent @albertov19  :)

**Comment by ColdDevil** [comment] 2021-03-22 00:49
Thanks @albertov19, I can confirm the import via `import "@openzeppelin/contracts/access/Ownable.sol"` is working when I set the `solidity.packageDefaultDependenciesDirectory` to an empty string!

**Comment by juanfranblanco** [comment] 2021-03-22 07:48
@ColdDevil yes that will be an issue, on discovering the node_modules, i might need to add a full path setting to allow workspaces to set their own environment

**Comment by vgeddes** [comment] 2021-03-24 17:44
Hey, I'm still getting the "File import callback not supported" error for Openzeppelin deps despite trying all the following and more:
* default settings
* full path to `node_modules` directory in `packageDefaultDependenciesDirectory`
* adding/removing `node_modules` from `packageDefaultDependenciesDirectory`
* adding/removing `contracts` from `solidity.packageDefaultDependenciesContractsDirectory`

I suspect its due to the fact that I'm using the workspace feature in VS code. I have this [monorepo](https://github.com/Snowfork/polkadot-ethereum), and each project within the monorepo is loaded as a workspace folder in VS code.

Our ethereum [contracts](https://github.com/Snowfork/polkadot-ethereum/tree/main/ethereum) are loaded into VS-code using this workspace folder configuration:

```javascript
{
  "folders": [
    {
      "name": "ethereum",
      "path": "polkadot-ethereum/ethereum"
    },
    // and more
  ]
}

**Comment by natanloterio** [comment] 2021-05-30 03:27
We could make the plugin run the solidity specifications from the current development environment ( truffle or hardhat .config files for instance ). 
This way, we can keep things simple.
What do you think?

**Comment by juanfranblanco** [comment] 2021-05-30 21:36
@natanloterio no that will add dependencies that will be required to be extended for every other new toolset, like dapptools, or even openzeppelin etc. That will be a maintenance nightmare. What it will be ideal is to have A standard for a project file.

**Comment by juanfranblanco** [comment] 2021-05-30 21:38
Closing this as it is solved, other suggestions can be put in another issue.

**Closed** 2021-05-30 21:38 UTC

**Comment by mpaler** [comment] 2022-01-18 20:26
@vgeddes did you ever figure out a solution for your setup? We're using workspaces as well and continue to have this problem. (ie. the solutions above aren't working)

**Comment by juanfranblanco** [comment] 2022-01-18 20:36
@vgeddes workspaces are supported now, although in a solution they all carry the same settings. So if you are using oz, your node_modules should be at the route of each workspace.

**Comment by juanfranblanco** [comment] 2022-01-18 20:37
@mpaler if you post a shot of your current workspace(s) structure and settings it might be able to understand the issue.

**Comment by mpaler** [comment] 2022-01-18 21:19
Hi @juanfranblanco 

<img width="334" alt="vscode" src="https://user-images.githubusercontent.com/352390/150020446-eea67763-78ff-4292-b088-0d780ede7313.png">

Thank you!
Michael

**Comment by juanfranblanco** [comment] 2022-01-18 21:24
In that scenario you could set a path to ```packages/hardhat/nodemodules```
or the root will work with the default ```node_modules```
either will to have the oz packages npm installed (stating the obvious)

**Comment by mpaler** [comment] 2022-01-18 21:45
@juanfranblanco the following solved it for me:

```
  "solidity.packageDefaultDependenciesDirectory": "packages/hardhat/node_modules",
```

**Comment by juanfranblanco** [comment] 2022-01-18 21:47
ah great! I guess the one at root may not have had the open zeppelin, but this matches better your project structure.

**Comment by sgnovo8** [comment] 2022-08-31 17:11
Hi, I'm following the OpenZeppelin Developing Smart Contracts "Learn" tutorial, using VSC, and all works fine but I can't seem to resolve a "problem" reported by VSC in connection with a line of code that imports "@openzeppelin/contracts/access/Ownable.sol".  

VSC identifies the problem as "Source '@openzeppelin/contracts/access/Ownable.sol' not found: File import callback not supported".

Does anyone know why I get this "problem" and how to resolve it?  Those @openzeppelin/contracts/access .sol files are all in my Learn directory, so why is VSC reporting otherwise?

I'm using Truffle.

I've already tried switching the default workspace compiler and modifying the package.json file in the juanblanco.solidity extension but neither change resolves anything.

**Comment by DrTenma1998** [comment] 2023-05-11 17:38
I'm just reverting my solidity extensions to 0.0135 and it worked for me you can try another version and you'll see

**Comment by juanfranblanco** [comment] 2023-05-12 04:40
@DrTenma1998 the extension defaults to node_modules as the main package folder. Do you have a remappings.txt file?

**Comment by juanfranblanco** [comment] 2023-05-12 05:30
@DrTenma1998  this is a new project just added open zeppelin modules

![solidity-simple-setup](https://github.com/juanfranblanco/vscode-solidity/assets/562371/e3d600e6-7280-4ef4-a43c-506061705a63)
![solidity-simple-setup-goTodefinition](https://github.com/juanfranblanco/vscode-solidity/assets/562371/7ec243b3-b348-4075-8830-dace09aebe37)
![solidity-simple-new-contract](https://github.com/juanfranblanco/vscode-solidity/assets/562371/08dec011-aa0b-40c6-8f51-601e1ea677c0)

**Comment by yashdev9274** [comment] 2023-10-05 11:27
hey @juanfranblanco I'm also getting this same error , can you pls help me too. 

here is my project structure:

![image](https://github.com/juanfranblanco/vscode-solidity/assets/72986960/c2c6e929-48da-4c5f-9c44-cdddf30d4bf7)
