### ISSUE TITLE
Intellisense/autocomplete is slow

### ISSUE THREAD

**Issue by MlSportsbook** [juanfranblanco/vscode-solidity#400] opened 2023-03-21 16:52 UTC
I love your extension and have used it a long time, thanks.

A few weeks ago, I installed a few updates, including a new version of the solidity extension.
Since then the autocomplete feature has become very slow (maybe 10 s. for a local variable or keyword). Compile time and other functionality is unchanged, but the lookup functionality is severely crippled.

I used other solidity extensions for some weeks now, but in my mind they are just not as good. Today I tried disabling all other extensions, disabled "as you type compilation..", disabled linting, disabled formatting etc. It still didn't help.

I finally reverted to "solidity  v0.0.141" extension version, and everything works well again.
Even with the previous mentioned functionality re-enabled, autocomplete/lookup is still fast and efficient.

I will be happy to help out providing info on my setup, if it is of any help to you.
Let me know what you want me to send/test.

Again, thanks for the nice work.

**Comment by jackqack** [comment] 2023-03-25 15:39
Same issue

**Comment by holic** [comment] 2023-04-12 16:11
dupe of #401 ?

**Comment by juanfranblanco** [comment] 2023-04-14 09:10
hi everyone, hopefully it is fixed now with the latest releases, let me know if you have further issues.

**Closed by juanfranblanco** 2023-04-14 09:10 UTC

**Comment by MlSportsbook** [comment] 2023-04-14 09:38
> hi everyone, hopefully it is fixed now with the latest releases, let me know if you have further issues.

Thanks, it's really appreciated.
I have approx 1 sec delay for the auto-complete suggestions to appear now. 
It's a little slower than the 0.0.141 version, but it's very acceptable.

**Comment by juanfranblanco** [comment] 2023-04-14 10:29
@MlSportsbook what libraries are you using? ie open zeppelin etc..

**Comment by MlSportsbook** [comment] 2023-04-14 10:42
"@ethersproject/abi": "^5.4.7",
    "@ethersproject/bytes": "^5.4.7",
    "@ethersproject/providers": "^5.4.7",
    "@nomicfoundation/hardhat-chai-matchers": "^1.0.6",
    "@nomiclabs/hardhat-ethers": "^2.0.5",
    "@nomiclabs/hardhat-etherscan": "^3.0.3",
    "@openzeppelin/contracts": "^4.6.0",
    "@openzeppelin/contracts-upgradeable": "^4.8.1",
    "@openzeppelin/hardhat-upgrades": "^1.22.1",
    "@typechain/ethers-v5": "^10.0.0",
    "@typechain/hardhat": "^6.0.0",
    "@types/chai": "^4.3.1",
    "@types/mocha": "^10.0.1",
    "@types/node": "17.0.31",
    "chai": "^4.3.6",
    "chai-ethers": "^0.0.1",
    "create-react-app": "^5.0.1",
    "dotenv": "^16.0.0",
    "eth-crypto": "^2.3.0",
    "ethers": "^5.7.2",
    "fs": "^0.0.1-security",
    "hardhat": "^2.9.3",
    "hardhat-contract-sizer": "^2.8.0",
    "hardhat-deploy": "^0.11.20",
    "hardhat-ethers": "^1.0.1",
    "hardhat-gas-reporter": "^1.0.8",
    "hardhat-preprocessor": "^0.1.5",
    "metamask-react": "^2.3.0",
    "path": "^0.12.7",
    "solidity-coverage": "^0.8.2",
    "ts-node": "^10.7.0",
    "typechain": "^8.0.0",
    "typescript": "^5.0.3"
    
I am not sure exactly what can influence it, so this is my full packagelist.
I can test some other, simpler projects, if it helps?
